#ifdef __SUNPRO_C
#pragma align 4 (taskbar_dialog_ui)
#endif
#ifdef __GNUC__
static const char taskbar_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char taskbar_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" ?><interface><requires lib=\"gtk+\" versio"
  "n=\"2.14\"/><!-- interface-requires libxfce4ui 0.0 --><!-- inter"
  "face-naming-policy toplevel-contextual --><object class=\"XfceTi"
  "tledDialog\" id=\"dialog\"><property name=\"can_focus\">False</p"
  "roperty><property name=\"title\" translatable=\"yes\">Task Bar</"
  "property><property name=\"icon_name\">gtk-properties</property><"
  "property name=\"type_hint\">normal</property><child internal-chi"
  "ld=\"vbox\"><object class=\"GtkVBox\" id=\"dialog-vbox2\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"spacing\">2</property><child i"
  "nternal-child=\"action_area\"><object class=\"GtkHButtonBox\" id"
  "=\"dialog-action_area2\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\""
  "layout_style\">end</property><child><object class=\"GtkButton\" "
  "id=\"close-button\"><property name=\"label\">gtk-close</property"
  "><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"receives_default\">True<"
  "/property><property name=\"use_action_appearance\">False</proper"
  "ty><property name=\"use_stock\">True</property></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">0</property></pac"
  "king></child><child><object class=\"GtkButton\" id=\"help-button"
  "\"><property name=\"label\">gtk-help</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">True</property><propert"
  "y name=\"use_action_appearance\">False</property><property name="
  "\"use_stock\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">1</property><property name=\"second"
  "ary\">True</property></packing></child></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"pack_type\">end</property><property n"
  "ame=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkVBox\" id=\"vbox1\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property na"
  "me=\"border_width\">6</property><property name=\"spacing\">6</pr"
  "operty><child><object class=\"GtkFrame\" id=\"frame3\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"label_xalign\">0</property><prope"
  "rty name=\"shadow_type\">none</property><child><object class=\"G"
  "tkAlignment\" id=\"alignment3\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property"
  " name=\"left_padding\">12</property><child><object class=\"GtkVB"
  "ox\" id=\"vbox3\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"border"
  "_width\">6</property><property name=\"spacing\">6</property><chi"
  "ld><object class=\"GtkCheckButton\" id=\"flat-buttons\"><propert"
  "y name=\"label\" translatable=\"yes\">Show _flat buttons</proper"
  "ty><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">Fal"
  "se</property><property name=\"use_action_appearance\">False</pro"
  "perty><property name=\"use_underline\">True</property><property "
  "name=\"draw_indicator\">True</property></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</"
  "property><property name=\"position\">1</property></packing></chi"
  "ld><child><object class=\"GtkCheckButton\" id=\"show-handle\"><p"
  "roperty name=\"label\" translatable=\"yes\">Show _handle</proper"
  "ty><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">Fal"
  "se</property><property name=\"use_action_appearance\">False</pro"
  "perty><property name=\"use_underline\">True</property><property "
  "name=\"draw_indicator\">True</property></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</"
  "property><property name=\"position\">2</property></packing></chi"
  "ld></object></child></object></child><child type=\"label\"><obje"
  "ct class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"label\" translatable=\"yes\">Appearance</property><a"
  "ttributes><attribute name=\"weight\" value=\"bold\"/></attribute"
  "s></object></child></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">True</property><property "
  "name=\"position\">0</property></packing></child><child><object c"
  "lass=\"GtkFrame\" id=\"frame1\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property"
  " name=\"label_xalign\">0</property><property name=\"shadow_type\""
  ">none</property><child><object class=\"GtkAlignment\" id=\"align"
  "ment1\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"left_padding\">1"
  "2</property><child><object class=\"GtkVBox\" id=\"vbox2\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><pr"
  "operty name=\"spacing\">6</property><child><object class=\"GtkHB"
  "ox\" id=\"hbox1\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"spacin"
  "g\">12</property></object><packing><property name=\"expand\">Tru"
  "e</property><property name=\"fill\">True</property><property nam"
  "e=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkCheckButton\" id=\"switch-workspace-on-unminimize\"><prop"
  "erty name=\"label\" translatable=\"yes\">Restore minimized windo"
  "ws to current _workspace</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"receives_default\">False</property><property name=\"us"
  "e_action_appearance\">False</property><property name=\"use_under"
  "line\">True</property><property name=\"draw_indicator\">True</pr"
  "operty></object><packing><property name=\"expand\">True</propert"
  "y><property name=\"fill\">True</property><property name=\"positi"
  "on\">1</property></packing></child><child><object class=\"GtkChe"
  "ckButton\" id=\"show-wireframes\"><property name=\"label\" trans"
  "latable=\"yes\">D_raw window frame when hovering a button</prope"
  "rty><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"receives_default\">Fa"
  "lse</property><property name=\"use_action_appearance\">False</pr"
  "operty><property name=\"use_underline\">True</property><property"
  " name=\"draw_indicator\">True</property></object><packing><prope"
  "rty name=\"expand\">True</property><property name=\"fill\">True<"
  "/property><property name=\"position\">2</property></packing></ch"
  "ild><child><object class=\"GtkCheckButton\" id=\"show-instances-"
  "on-hover\"><property name=\"label\" translatable=\"yes\">Show in"
  "stances list when hovering a button</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</prope"
  "rty><property name=\"receives_default\">False</property><propert"
  "y name=\"use_action_appearance\">False</property><property name="
  "\"xalign\">0.51999998092651367</property><property name=\"yalign"
  "\">0.51999998092651367</property><property name=\"draw_indicator"
  "\">True</property></object><packing><property name=\"expand\">Tr"
  "ue</property><property name=\"fill\">True</property><property na"
  "me=\"position\">3</property></packing></child><child><object cla"
  "ss=\"GtkHBox\" id=\"hbox2\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><child><objec"
  "t class=\"GtkLabel\" id=\"label4\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"label\" translatable=\"yes\">Drag-n-drop: </property>"
  "</object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkComboBox\""
  " id=\"drag-button\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"mode"
  "l\">liststore1</property><child><object class=\"GtkCellRendererT"
  "ext\" id=\"cellrenderertext1\"/><attributes><attribute name=\"te"
  "xt\">0</attribute></attributes></child></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"position\">1</property></packing></ch"
  "ild></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\""
  ">4</property></packing></child></object></child></object></child"
  "><child type=\"label\"><object class=\"GtkLabel\" id=\"label3\">"
  "<property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"y"
  "es\">Behaviour</property><attributes><attribute name=\"weight\" "
  "value=\"bold\"/></attributes></object></child></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packin"
  "g></child><child><object class=\"GtkFrame\" id=\"frame2\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label_xalign\">0</property><pr"
  "operty name=\"shadow_type\">none</property><child><object class="
  "\"GtkAlignment\" id=\"alignment2\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"left_padding\">12</property><child><object class=\"Gt"
  "kVBox\" id=\"vbox4\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"bor"
  "der_width\">6</property><property name=\"spacing\">6</property><"
  "child><object class=\"GtkCheckButton\" id=\"include-all-workspac"
  "es\"><property name=\"label\" translatable=\"yes\">Show windows "
  "from _all workspaces or viewports</property><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">False</property><property "
  "name=\"use_action_appearance\">False</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">True"
  "</property><property name=\"fill\">True</property><property name"
  "=\"position\">0</property></packing></child><child><object class"
  "=\"GtkCheckButton\" id=\"include-all-monitors\"><property name=\""
  "label\" translatable=\"yes\">Show windows from all mo_nitors</pr"
  "operty><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"use_action_appearance\">False<"
  "/property><property name=\"use_underline\">True</property><prope"
  "rty name=\"draw_indicator\">True</property></object><packing><pr"
  "operty name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">1</property></packing><"
  "/child><child><object class=\"GtkCheckButton\" id=\"show-only-mi"
  "nimized\"><property name=\"label\" translatable=\"yes\">Show onl"
  "y _minimized windows</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_ac"
  "tion_appearance\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</proper"
  "ty></object><packing><property name=\"expand\">True</property><p"
  "roperty name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child></object></child></object></child"
  "><child type=\"label\"><object class=\"GtkLabel\" id=\"label2\">"
  "<property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"label\" translatable=\"y"
  "es\">Filtering</property><attributes><attribute name=\"weight\" "
  "value=\"bold\"/></attributes></object></child></object><packing>"
  "<property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">2</property></packin"
  "g></child></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"fill\">True</property><property name=\"po"
  "sition\">1</property></packing></child></object></child><action-"
  "widgets><action-widget response=\"0\">close-button</action-widge"
  "t><action-widget response=\"0\">help-button</action-widget></act"
  "ion-widgets></object><object class=\"GtkListStore\" id=\"liststo"
  "re1\"><columns><!-- column-name Text1 --><column type=\"gchararr"
  "ay\"/></columns><data><row><col id=\"0\" translatable=\"yes\">Le"
  "ft button</col></row><row><col id=\"0\" translatable=\"yes\">Mid"
  "dle button</col></row></data></object></interface>"
};
static const unsigned taskbar_dialog_ui_length = 12664u;
